services:
  app:
    image: golang:1.23-alpine
    working_dir: /app
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=orders
      - DB_DRIVER=mysql
      - WEB_SERVER_PORT=:8000
      - GRPC_SERVER_PORT=50051
      - GRAPHQL_SERVER_PORT=8080
    ports:
      - "8080:8080"
      - "8000:8000"
      - "50051:50051"
    volumes:
        - .:/app
    command: sh -c "sleep 60 && cd cmd/ordersystem && go run main.go wire_gen.go"
    restart: on-failure

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./migrations/001_create_orders_table.sql:/docker-entrypoint-initdb.d/001_create_orders_table.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest